version: '3'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=aasbb
      - WORDPRESS_DB_PASSWORD=superStrongPassword
      - WORDPRESS_DB_USER=aasbb
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MARIADB_DATABASE=aasbb
      - MARIADB_PASSWORD=superStrongPassword
      - MARIADB_ROOT_PASSWORD=superStrongPasswordforRoot
      - MARIADB_USER=aasbb
